### ISSUE TITLE
Initialize and Content Security Policy

### ISSUE THREAD

**Issue by bmvantunes** [hotjar/hotjar-js#13]
When we try to call initialize using Hotjar.init(projectId, version) this library will create an inline script, which will trigger strict content security policies.

In order to avoid that, init should receive a third parameter to attach a nonce to the generated script.

Would you accept a PR with this feature?

**Comment by seanparmelee** [comment]
I'm too interested in this.

@bmvantunes did you close this because you ended up instrumenting hotjar another way?

**Comment by bmvantunes** [comment]
Sorry I was not aware I closed this - I will reopen

**Comment by bmvantunes** [comment]
There's a PR open #16 that will solve our problem :)
