### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by juliano-nunes** [hotjar/hotjar-js#18]
Hi, your source map point to the non existent src folder, can you bundle the next version fixing that?!

![image](https://user-images.githubusercontent.com/22858307/214119463-63500fef-26c7-4c69-85a2-d667e37648a2.png)

**Comment by olan-go2** [comment]
@juliano-nunes I have the same issue

**Comment by blicksky** [comment]
This is related to https://github.com/facebook/create-react-app/discussions/11767

**Comment by juliano-nunes** [comment]
@blicksky this CRA issue treats about ignore warnings that are completely valid because this package is not being built with source code, so the source-map-loader it's not able to generate the source maps because the dist file of this package refers to a non existent folder.

**Comment by blicksky** [comment]
That's right, and `@hotjar/browser` is one of those packages that has a source map pointing to code that's not included in the package. One perspective is that the warning is too prominent for a relatively common occurrence, but there's no way to selectively ignore warnings and only the package maintainer has the ability to correct the underlying issue. 

There's no reason to include a source map in a package unless it can actually map to source code, so this package should be updated to either include the source code or to remove the source map references to it.

**Comment by hereismass** [comment]
Fixed with #19 , closing the issue
