### ISSUE TITLE
hj.event.signal function error

### ISSUE THREAD

**Issue by Amilson** [hotjar/hotjar-js#8]
Hi folks.
I've been facing an issue with hotjar last couple of days.

I contacted the support team (btw always answering me properly, thanks for that) but until now, my problem wasn't solved.

Well, seems that when my clients run my application with "Block third-party" on their browsers, and for that reason some of your bundled scripts are not load properly.
![image](https://user-images.githubusercontent.com/10110065/126055779-5f22ad7f-8cd2-42bf-baa0-02f9e091a237.png)
(this is my localhost environment, but also happen in production)

For fix that, I've added some conditions to your static file to prevent this issue to be fired by the browser and also not showing in the console as a error. To my fix run properly I copied this script to my assets.

Take a look in this conditions:
![image](https://user-images.githubusercontent.com/10110065/126055731-72bb9fc6-ff4d-4ca5-bc62-3bcdcc2897cd.png)
The `hj.event.signal('varsLoaded')` is not fired if this method is unavailable.

I also will reply to support with this solution and I am looking forward to hear from you.
If you need more tests or evidences, I'm here.

**Comment by Amilson** [comment]
`u.addEventListener && (hj.scriptDomain = e, (d = u.createElement('script')).async = 1, d.src = hj.scriptDomain + t, d.charset = 'utf-8', c.appendChild(d), _ = ['iframe#_hjRemoteVarsFrame {', 'display: none !important; width: 1px !important; height: 1px !important; opacity: 0 !important; pointer-events: none !important;', '}'], (l = u.createElement('style')).type = 'text/css', l.styleSheet ? l.styleSheet.cssText = _.join('') : l.appendChild(u.createTextNode(_.join(''))), c.appendChild(l), (p = u.createElement('iframe')).style.cssText = _[1], p.name = '_hjRemoteVarsFrame', p.title = '_hjRemoteVarsFrame', p.id = '_hjRemoteVarsFrame', p.src = `https://${window._hjSettings.varsHost || 'vars.hotjar.com'}/box-25a418976ea02a6f393fbbe77cec94bb.html`, p.onload = function () {
          s.varsLoaded = !0, typeof hj !== 'undefined' && hj.event && hj.event.signal && typeof hj.event.signal === 'function' && hj.event.signal('varsLoaded');
        }, s.varsJar = p, u.readyState === 'interactive' || u.readyState === 'complete' || u.readyState === 'loaded' ? f() : u.addEventListener('DOMContentLoaded', f), s.revision = 'f52d759380c7', window.hjBootstrap = s);`

**Comment by arrwhidev** [comment]
Hey @Amilson 👋 

Thanks for reaching out.

To help with our investigation into this issue, can you provide us with some example code or a URL so that we can reproduce this issue, please?

**Comment by Amilson** [comment]
Hey @arrwhidev.

Here a example code:
https://stackblitz.com/edit/angular-ivy-yybkpb

And also my application:
https://intercement.monkey.exchange/new/authentication/email/login

But, in production I solved by adding the condition "typeof hj.event.signal === 'function'" and load the new script by application assets, and my application doesn't emit this error anymore.

Take a look at stackblitz, I replaced the hjid and I also added the hotjar-hjid-hjsv.js example in assets folder.

**My environment**:
Browser: Firefox 90.0.2 (64-bits)
OS: Windows 10

**Some of my clients environment**:
1:
![image](https://user-images.githubusercontent.com/10110065/127778957-780b140f-e2e3-4458-95e7-d8e90e8a2137.png)
2:
![image](https://user-images.githubusercontent.com/10110065/127778964-adf82f49-0bbb-43b2-824c-bc39a8adc3d8.png)

**Comment by ejulianova** [comment]
Hey @Amilson, thanks for providing all this info. Unfortunately we still didn't manage to repro the issue. Tried the following:
- blocking `scripts.hotjar.com`
- blocking 3d party cookies
- blocking all tracking
- tested in Chrome, Firefox and Brave

However none of the above resulted in throwing this exception. The fact that `hj.event` is defined, but `hj.event.signal` isn't means that the script is not getting blocked, but there might be either:
- another exception happening before the signal method is defined or
- something overriding the method

Can you advise if there are any additional steps to repro the issue? Is there a particular third party plugin that you're using?

**Comment by Amilson** [comment]
Hey @ejulianova 

My application has the following third party plugins:
- Zendesk (https://www.zendesk.com)
- Usetiful (https://www.usetiful.com)
- Google charts (https://www.gstatic.com/charts/loader.js)
- Status Page (https://www.atlassian.com/software/statuspage)
- Datadog

I only deploy my application to production and during the day I get this errors.

Can you try again? 

https://intercement.monkey.exchange/new/authentication/email/login

Today these issues show up again.
Take a look:
![image](https://user-images.githubusercontent.com/10110065/128799169-18b2a4b6-4086-450e-bda1-dedf86f88ae9.png)

**Comment by ejulianova** [comment]
Hi @Amilson! Apologies for the late response! We've deployed a fix within the tracking code script itself (i.e. you no need to update the npm package). Thank you for reporting this issue and all the details. This has been very helpful! 🙂
