### ISSUE TITLE
Add Support for Events API

### ISSUE THREAD

**Issue by bobbyg603** [hotjar/hotjar-js#9]
We would prefer to use this package instead of the generated script tag via the site. Unfortunately, there is no formal support for adding events in this package that matches the Events API [doc](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference) on the hotjar site.

Workaround is to import `executeHotjarCommand` from utils (awkward) and override the provided type to use the 'event' command (also awkward).

Are there any plans to improve support in this SDK? It would be a much nicer experience in web apps than the current auto-generated old-school script tag...

Thanks!

**Comment by arrwhidev** [comment]
@bobbyg603 Your MR has been merged and published to [npm (v1.0.4)](https://www.npmjs.com/package/@hotjar/browser/v/1.0.4).

Thank you for raising & implementing this change, and thanks for using Hotjar!

**Comment by bobbyg603** [comment]
@arrwhidev thank you for merging this change! hotjar has been great so far, thanks for your support!
